services:
  - type: web
    name: pasteleria-tradicional
    runtime: static
    branch: main
    autoDeployTrigger: commit
    buildCommand: test -f aplicaciones.html && test -f login.html && test -f css/estilos.css && echo "static 2026-09-30"
    staticPublishPath: .
